# Generated by Django 4.2.4 on 2023-09-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ('-created_at', 'payed')},
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='num_reference',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
